FROM node:alpine

WORKDIR /app

COPY package*.json .


#  RUN npm ci --only=production // instala las dependencias necesarias sin las de desarrollo
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]